#!/bin/sh

# mylatexdiff
# -----------
#
# A shell script wrapper around `latexdiff` for use with `git difftool`.
#
# `latexdiff` will determine and markup differences between two latex files.
# When run, `mylatexdiff` will internally run `latexdiff`, compile the output with
# `pdflatex` and then display the resulting file with `xpdf`.
#
# Author:  valentin.haenel@gmx.de (2011)
# Licence: wtfpl (Do what the fuck you want to public Licence)
#
# Configuring for use with git difftool
# -------------------------------------

# Simply put in your $PATH, and then do:
#
#     git difftool --extcmd=mylatexdiff <arguments>
#
# You may want to configure the following option to stop the prompt:
#
#     git config --global difftool.prompt false
#
# And perhaps also the following alias to spare you some typing and typos:
#
#     git config --global alias.tdiff 'difftool --extcmd=mylatexdiff'
#
# Examples:
#
#     git tdiff -- report.tex
#     git tdiff HEAD~5.. -- report.tex

if ! which latexdiff ; then
    echo "fatal: 'latexdiff' not found in \$PATH"
    # TODO this does not cause git difftool to exit with non-zero status.
    exit 1
fi

OLD="$1"
NEW="$2"

# TODO perhaps move to the directory that the file is in
# to make sure relative imports are handled correctly
# Probably best to generate a random filename, and then check that it doesn't
# exist
latexdiff --ignore-warnings $OLD $NEW >> diff.tex
# TODO make compiler configurable via a git-option
pdflatex diff.tex
# TODO make viewer configurable via a git-option
xpdf diff.pdf
# TODO clean up the mess we made we could just delete all files
# called diff.* but maybe, just maybe that file exist already in the git-repo
